export default {
  login: 'shawlu95',
  id: 32722220,
  node_id: 'MDQ6VXNlcjMyNzIyMjIw',
  avatar_url: 'https://avatars.githubusercontent.com/u/32722220?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/shawlu95',
  html_url: 'https://github.com/shawlu95',
  followers_url: 'https://api.github.com/users/shawlu95/followers',
  following_url: 'https://api.github.com/users/shawlu95/following{/other_user}',
  gists_url: 'https://api.github.com/users/shawlu95/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/shawlu95/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/shawlu95/subscriptions',
  organizations_url: 'https://api.github.com/users/shawlu95/orgs',
  repos_url: 'https://api.github.com/users/shawlu95/repos',
  events_url: 'https://api.github.com/users/shawlu95/events{/privacy}',
  received_events_url: 'https://api.github.com/users/shawlu95/received_events',
  type: 'User',
  site_admin: false,
  name: 'Shaw Lu',
  company: 'Stanford University',
  blog: 'https://www.linkedin.com/in/shawlu95/',
  location: 'Stanford, CA',
  email: null,
  hireable: true,
  bio: 'Writing good code',
  twitter_username: null,
  public_repos: 97,
  public_gists: 29,
  followers: 116,
  following: 4,
  created_at: '2017-10-12T00:03:01Z',
  updated_at: '2022-05-21T21:02:41Z',
};
